/* Auto-generated by scripts/sync-hero-images.mjs — do not edit */
export const heroSlidesGenerated = [
  {
    "src": "/images/hero/ai-and-cloud-technology-visuals.jpg",
    "alt": "ai and cloud technology visuals"
  },
  {
    "src": "/images/hero/artificial-intelligence.jpg",
    "alt": "artificial intelligence"
  },
  {
    "src": "/images/hero/business-professionals-discussing-technology.jpg",
    "alt": "business professionals discussing technology"
  },
  {
    "src": "/images/hero/digital-brain-graphics.jpg",
    "alt": "digital brain graphics"
  },
  {
    "src": "/images/hero/enterprise-image.jpg",
    "alt": "enterprise image"
  },
  {
    "src": "/images/hero/executive-meeting-with-digital-screens.jpg",
    "alt": "executive meeting with digital screens"
  },
  {
    "src": "/images/hero/large-server-room-with-engineers.jpg",
    "alt": "large server room with engineers"
  },
  {
    "src": "/images/hero/machine-learning.jpg",
    "alt": "machine learning"
  },
  {
    "src": "/images/hero/modern-digital-workspace.jpg",
    "alt": "modern digital workspace"
  }
] as const;
