/* Auto-generated by scripts/sync-hero-images.mjs — do not edit */
export const heroSlidesGenerated = [
  {
    "src": "/images/hero/ai-and-cloud-technology-visuals.jpg",
    "alt": "AI and cloud technology visuals"
  },
  {
    "src": "/images/hero/artificial-intelligence.jpg",
    "alt": "Artificial Intelligence"
  },
  {
    "src": "/images/hero/business-professionals-discussing-technology.jpg",
    "alt": "Business professionals discussing technology"
  },
  {
    "src": "/images/hero/digital-brain-graphics.jpg",
    "alt": "Digital brain graphics"
  },
  {
    "src": "/images/hero/enterprise-image.jpg",
    "alt": "enterprise image"
  },
  {
    "src": "/images/hero/executive-meeting-with-digital-screens.jpg",
    "alt": "Executive meeting with digital screens"
  },
  {
    "src": "/images/hero/large-server-room-with-engineers.jpg",
    "alt": "Large server room with engineers"
  },
  {
    "src": "/images/hero/machine-learning.jpg",
    "alt": "Machine Learning"
  },
  {
    "src": "/images/hero/modern-digital-workspace.jpg",
    "alt": "Modern digital workspace"
  }
] as const;
