export const site = {
  companyName: "Synergy Computers",
  tagline: "IT Solutions Pakistan",
  legalName: "Synergy Computers (Pvt.) Ltd.",
  description:
    "Pakistan's premium IT solutions provider — infrastructure, enterprise applications, security, and 24×7 support for over 40 years.",
  email: "info@synergy.net.pk",
  phoneDisplay: "021-34527060",
  phoneTel: "+922134527060",
  phones: ["021-34527060", "021-34540908", "021-34547068"],
  addressLine: "56-D, K.D.A Scheme No.1 Main Miran Muhammad Shah Road",
  addressCity: "Karachi",
  addressCountry: "Pakistan",
  socialLinkedin: "https://www.linkedin.com/company/synergy-computers/",
  socialFacebook: "https://www.facebook.com/SynergyCompuetsPvtLtd/",
  socialTwitter: "",
  socialInstagram: "",
  googleMapsUrl: "",
  businessHours: "Mon–Fri, 9:00 AM – 6:00 PM",
  copyright: "© Synergy Computers (Pvt.) Ltd. All rights reserved.",
  mission: "",
  vision: "",
  nav: [
    { id: "services", label: "Services", href: "/services" },
    { id: "partners", label: "Partners", href: "/partners" },
    {
      id: "about",
      label: "About",
      href: "/about",
      children: [
        { id: "who", label: "Who We Are", href: "/about#who-we-are" },
        { id: "leadership", label: "Our Leadership", href: "/about#leadership" },
        { id: "accomplishments", label: "Our Accomplishments", href: "/about#accomplishments" },
      ],
    },
    { id: "careers", label: "Careers", href: "/careers" },
    { id: "resources", label: "Resources", href: "/resources" },
  ],
};
