"use client";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { listOrdered, updateDocById } from "@/lib/admin/crud";
import { COLLECTIONS, type ContactMessage } from "@/lib/firebase/collections";
import { AdminPageSkeleton } from "@/components/admin/AdminSkeleton";
import { AdminPageHeader, Card, EmptyState, SecondaryButton, StatusBadge, inputClass } from "@/components/admin/ui";
const csv = (rows: Record<string, unknown>[], name: string) => { const cols=Object.keys(rows[0]||{}); const text=[cols.join(","),...rows.map(r=>cols.map(c=>JSON.stringify(r[c]??"")).join(","))].join("\n"); const a=document.createElement("a"); a.href=URL.createObjectURL(new Blob([text],{type:"text/csv"}));a.download=name;a.click();URL.revokeObjectURL(a.href); };
export function MessagesManager(){const [items,setItems]=useState<ContactMessage[]>([]),[query,setQuery]=useState(""),[loading,setLoading]=useState(true);const load=async()=>{setLoading(true);try{setItems(await listOrdered<ContactMessage>(COLLECTIONS.messages,"createdAt"))}catch(e){toast.error(e instanceof Error?e.message:"Failed to load messages")}finally{setLoading(false)}};useEffect(()=>{void load()},[]);const filtered=useMemo(()=>items.filter(x=>`${x.name} ${x.email} ${x.message}`.toLowerCase().includes(query.toLowerCase())),[items,query]);const status=async(item:ContactMessage,value:ContactMessage["status"])=>{if(!item.id)return;try{await updateDocById(COLLECTIONS.messages,item.id,{status:value});await load()}catch(e){toast.error(e instanceof Error?e.message:"Update failed")}};if(loading)return <AdminPageSkeleton/>;return <div className="space-y-6"><AdminPageHeader title="Messages" description="Review incoming contact requests." actions={<SecondaryButton onClick={()=>csv(items as Record<string,unknown>[],"messages.csv")}>Export CSV</SecondaryButton>}/><Card className="p-3"><input className={inputClass} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search messages…"/></Card>{!filtered.length?<EmptyState title="No messages" description="Contact form submissions will appear here."/>:<div className="space-y-3">{filtered.map(item=><Card key={item.id} className="flex flex-wrap justify-between gap-3 py-4"><div className="max-w-2xl"><p className="font-medium">{item.name} <span className="font-normal text-zinc-500">({item.email})</span></p><p className="mt-1 whitespace-pre-wrap text-sm">{item.message}</p><div className="mt-2"><StatusBadge status={item.status}/></div></div><div className="flex gap-2">{item.status!=="read"&&<SecondaryButton onClick={()=>void status(item,"read")}>Mark read</SecondaryButton>}{item.status==="read"&&<SecondaryButton onClick={()=>void status(item,"unread")}>Mark unread</SecondaryButton>}{item.status!=="archived"&&<SecondaryButton onClick={()=>void status(item,"archived")}>Archive</SecondaryButton>}</div></Card>)}</div>}</div>}
