"use client";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import type { NavItemDoc } from "@/lib/admin/types";
import { getById, upsertSingleton } from "@/lib/admin/crud";
import { COLLECTIONS, DOCS } from "@/lib/firebase/collections";
import { AdminPageSkeleton } from "@/components/admin/AdminSkeleton";
import { AdminPageHeader, Card, Field, PrimaryButton, SecondaryButton, inputClass } from "@/components/admin/ui";
export function NavigationManager(){const [items,setItems]=useState<NavItemDoc[]>([]),[loading,setLoading]=useState(true);useEffect(()=>{getById<{items?:NavItemDoc[]}>(COLLECTIONS.navigation,DOCS.navigationPrimary).then(x=>setItems(x?.items||[])).catch(()=>toast.error("Failed to load navigation")).finally(()=>setLoading(false))},[]);const update=(i:number,key:keyof NavItemDoc,value:string|boolean)=>setItems(items.map((x,n)=>n===i?{...x,[key]:value}:x));const move=(i:number,d:number)=>{const n=i+d;if(n<0||n>=items.length)return;const next=[...items];[next[i],next[n]]=[next[n],next[i]];setItems(next)};if(loading)return <AdminPageSkeleton/>;return <div className="space-y-6"><AdminPageHeader title="Navigation" description="Manage primary navigation links and their order." actions={<PrimaryButton onClick={async()=>{await upsertSingleton(COLLECTIONS.navigation,DOCS.navigationPrimary,{items});toast.success("Navigation saved")}}>Save navigation</PrimaryButton>}/><Card className="space-y-4">{items.map((item,i)=><div key={item.id} className="grid gap-3 border-b pb-4 md:grid-cols-5"><Field label="Label"><input className={inputClass} value={item.label} onChange={e=>update(i,"label",e.target.value)}/></Field><Field label="URL"><input className={inputClass} value={item.href} onChange={e=>update(i,"href",e.target.value)}/></Field><Field label="External"><input type="checkbox" checked={Boolean(item.external)} onChange={e=>update(i,"external",e.target.checked)}/></Field><div className="flex items-end gap-2"><SecondaryButton onClick={()=>move(i,-1)}>Up</SecondaryButton><SecondaryButton onClick={()=>move(i,1)}>Down</SecondaryButton><SecondaryButton onClick={()=>setItems(items.filter((_,n)=>n!==i))}>Remove</SecondaryButton></div><p className="self-end text-xs text-zinc-500">{item.children?.length||0} nested children retained</p></div>)}<SecondaryButton onClick={()=>setItems([...items,{id:crypto.randomUUID(),label:"New link",href:"/"}])}>Add link</SecondaryButton></Card></div>}
