"use client";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import type { NewsletterDoc } from "@/lib/admin/types";
import { deleteDocById, listOrdered } from "@/lib/admin/crud";
import { COLLECTIONS } from "@/lib/firebase/collections";
import { AdminPageSkeleton } from "@/components/admin/AdminSkeleton";
import { ConfirmDialog } from "@/components/admin/ConfirmDialog";
import { AdminPageHeader, Card, EmptyState, SecondaryButton, StatusBadge, inputClass } from "@/components/admin/ui";
const exportCsv=(rows:NewsletterDoc[])=>{const content=["email,name,status",...rows.map(x=>[x.email,x.name||"",x.status].map(v=>JSON.stringify(v)).join(","))].join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([content],{type:"text/csv"}));a.download="newsletter-subscribers.csv";a.click();};
export function NewsletterManager(){const [items,setItems]=useState<NewsletterDoc[]>([]),[query,setQuery]=useState(""),[loading,setLoading]=useState(true),[deleting,setDeleting]=useState<NewsletterDoc|null>(null);const load=async()=>{setLoading(true);try{setItems(await listOrdered<NewsletterDoc>(COLLECTIONS.newsletter,"createdAt"))}catch(e){toast.error(e instanceof Error?e.message:"Failed to load subscribers")}finally{setLoading(false)}};useEffect(()=>{void load()},[]);const filtered=useMemo(()=>items.filter(x=>`${x.email} ${x.name||""}`.toLowerCase().includes(query.toLowerCase())),[items,query]);const remove=async()=>{if(!deleting?.id)return;try{await deleteDocById(COLLECTIONS.newsletter,deleting.id);setDeleting(null);await load();toast.success("Subscriber deleted")}catch(e){toast.error(e instanceof Error?e.message:"Delete failed")}};if(loading)return <AdminPageSkeleton/>;return <div className="space-y-6"><AdminPageHeader title="Newsletter" description="Manage newsletter subscribers." actions={<SecondaryButton onClick={()=>exportCsv(items)}>Export CSV</SecondaryButton>}/><Card className="p-3"><input className={inputClass} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search subscribers…"/></Card>{!filtered.length?<EmptyState title="No subscribers" description="New signups will appear here."/>:<div className="space-y-3">{filtered.map(item=><Card key={item.id} className="flex items-center justify-between py-4"><div><p className="font-medium">{item.email}</p><p className="text-sm text-zinc-500">{item.name||"No name"}</p><StatusBadge status={item.status}/></div><SecondaryButton className="text-red-600" onClick={()=>setDeleting(item)}>Delete</SecondaryButton></Card>)}</div>}<ConfirmDialog open={Boolean(deleting)} title="Delete subscriber?" confirmLabel="Delete" danger onConfirm={()=>void remove()} onCancel={()=>setDeleting(null)}/></div>}
