"use client";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import type { ThemeTokens } from "@/lib/admin/types";
import { DEFAULT_THEME } from "@/lib/admin/types";
import { getById, upsertSingleton } from "@/lib/admin/crud";
import { invalidateCmsCache } from "@/lib/cms/cache";
import { requestPublicCmsRevalidate } from "@/lib/cms/revalidate-client";
import { COLLECTIONS, DOCS } from "@/lib/firebase/collections";
import { AdminPageSkeleton } from "@/components/admin/AdminSkeleton";
import { AdminPageHeader, Card, Field, PrimaryButton, inputClass } from "@/components/admin/ui";
export function ThemeManager(){const [form,setForm]=useState<ThemeTokens>(DEFAULT_THEME),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);useEffect(()=>{getById<ThemeTokens>(COLLECTIONS.theme,DOCS.themeTokens).then(x=>x&&setForm({...DEFAULT_THEME,...x})).catch(()=>toast.error("Failed to load theme")).finally(()=>setLoading(false))},[]);if(loading)return <AdminPageSkeleton/>;const css=Object.fromEntries(Object.entries(form).filter(([,v])=>typeof v==="string").map(([k,v])=>[`--${k.replace(/[A-Z]/g,m=>`-${m.toLowerCase()}`)}`,v]));return <div className="space-y-6"><AdminPageHeader title="Theme" description="Configure global theme tokens." actions={<PrimaryButton disabled={saving} onClick={async()=>{setSaving(true);try{await upsertSingleton(COLLECTIONS.theme,DOCS.themeTokens,form);invalidateCmsCache("theme");void requestPublicCmsRevalidate(["cms-theme"]);toast.success("Theme saved")}catch(e){toast.error(e instanceof Error?e.message:"Save failed")}finally{setSaving(false)}}}>{saving?"Saving…":"Save theme"}</PrimaryButton>}/><Card><div className="grid gap-4 md:grid-cols-2">{Object.entries(form).map(([key,value])=><Field key={key} label={key.replace(/[A-Z]/g," $&")}><input type={key.includes("Mode")||key==="animationsEnabled"?"text":key.includes("color")||["primary","secondary","accent","text","background","surface","border","buttonBg","buttonText"].includes(key)?"color":"text"} className={inputClass} value={String(value)} onChange={e=>setForm({...form,[key]:key==="animationsEnabled"?e.target.value==="true":e.target.value} as ThemeTokens)}/></Field>)}</div></Card><Card><h2 className="mb-3 font-semibold">Preview</h2><div style={css} className="rounded-[var(--border-radius)] border border-[var(--border)] bg-[var(--surface)] p-6 text-[var(--text)] shadow-[var(--shadow)]"><p className="text-lg font-semibold">Synergy Computers</p><p style={{color:"var(--text-muted)"}}>Theme token preview</p><button style={{background:"var(--button-bg)",color:"var(--button-text)"}} className="mt-4 rounded px-4 py-2">Sample button</button></div></Card></div>}
