export const adminModuleStubs = [
  {
    slug: "blogs",
    title: "Blogs",
    description: "Professional blog CMS with drafts, scheduling, categories, tags, SEO, and a rich text editor.",
    phase: 3,
  },
  {
    slug: "alumni",
    title: "Alumni",
    description: "Manage alumni profiles, batches, companies, and featured stories.",
    phase: 4,
  },
  {
    slug: "leadership",
    title: "Board of Directors",
    description: "Add, edit, reorder, and publish board members with photos and bios.",
    phase: 4,
  },
  {
    slug: "services",
    title: "Services",
    description: "CRUD for service offerings, icons, banners, categories, and SEO.",
    phase: 4,
  },
  {
    slug: "testimonials",
    title: "Testimonials",
    description: "Collect and feature client reviews with ratings and company details.",
    phase: 4,
  },
  {
    slug: "clients",
    title: "Clients",
    description: "Client logos, categories, websites, and display ordering.",
    phase: 4,
  },
  {
    slug: "gallery",
    title: "Gallery",
    description: "Albums, multi-image upload, reorder, and lazy-loaded public galleries.",
    phase: 4,
  },
  {
    slug: "events",
    title: "Events",
    description: "Event banners, dates, locations, registration links, and galleries.",
    phase: 5,
  },
  {
    slug: "careers",
    title: "Careers",
    description: "Job openings, departments, locations, skills, and application intake.",
    phase: 5,
  },
  {
    slug: "media",
    title: "Media Library",
    description: "Central Firebase Storage media browser with folders, search, replace, and compression.",
    phase: 2,
  },
  {
    slug: "faq",
    title: "FAQ",
    description: "Frequently asked questions grouped by category with sort order.",
    phase: 5,
  },
  {
    slug: "messages",
    title: "Contact Messages",
    description: "Inbox for contact form submissions with unread/read/archive and CSV export.",
    phase: 5,
  },
  {
    slug: "newsletter",
    title: "Newsletter Subscribers",
    description: "Store subscribers, search, delete, and export CSV lists.",
    phase: 5,
  },
  {
    slug: "users",
    title: "Users",
    description: "Manage admin users and roles. Seed your first admin with npm run admin:seed.",
    phase: 1,
  },
  {
    slug: "seo",
    title: "SEO Manager",
    description: "Site-wide and per-page SEO, Open Graph, Twitter cards, and JSON-LD.",
    phase: 6,
  },
  {
    slug: "theme",
    title: "Theme Customizer",
    description: "Live brand colors, fonts, radius, spacing, and dark mode tokens.",
    phase: 6,
  },
  {
    slug: "navigation",
    title: "Navigation Menu",
    description: "Drag-and-drop primary navigation with nested menus and visibility controls.",
    phase: 6,
  },
  {
    slug: "footer",
    title: "Footer",
    description: "Editable footer link groups and legal/copyright blocks.",
    phase: 6,
  },
  {
    slug: "analytics",
    title: "Analytics",
    description: "Visitors, popular pages, form submissions, and traffic charts.",
    phase: 6,
  },
  {
    slug: "system",
    title: "Settings",
    description: "System preferences, audit log access, and CMS configuration.",
    phase: 1,
  },
] as const;
